FROM python:3.8-slim

RUN apt-get update && apt-get install -y git gcc libpcre3-dev
RUN pip install pip==24.0

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt

CMD celery -A tipi_tasks worker -B -l info
